name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Create tfvars file
        run: |
          cat <<EOF > secrets.auto.tfvars
          project                       = "${{ secrets.PROJECT_ID }}"
          region                        = "${{ secrets.REGION }}"
          songs_secret_manager_name     = "${{ secrets.SONGS_SECRET_MANAGER_NAME }}"
          EOF

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Validate Terraform
        run: terraform validate
        working-directory: terraform

      - name: Plan Terraform
        run: terraform plan
        working-directory: terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: terraform
