name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/terraform-sa.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Write service account JSON
        run: |
          cat <<EOF > ${{ github.workspace }}/terraform-sa.json
          ${{ secrets.TERRAFORM_SA }}
          EOF

      - name: Create tfvars file
        run: |
          cat <<EOF > ${{ github.workspace }}/terraform/secrets.tfvars
          project                       = "${{ secrets.PROJECT_ID }}"
          region                        = "${{ secrets.REGION }}"
          songs_secret_manager_name     = "${{ secrets.SONGS_SECRET_MANAGER_NAME }}"
          EOF

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Validate Terraform
        run: terraform validate
        working-directory: terraform

      - name: Plan Terraform
        run: terraform plan -var-file="secrets.tfvars"
        working-directory: terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve -var-file="secrets.tfvars"
        working-directory: terraform
