name: Testing environment

on:
  push:
    branches:
      - '**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/terraform-sa.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Testing variables
        run: |
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}"
          echo "REGION=${{ secrets.REGION }}"
          echo "SONGS_SECRET_MANAGER_NAME=${{ secrets.SONGS_SECRET_MANAGER_NAME }}"